name: Deploy to UAT
on:
  push:
    branches:
      - uat

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          npm ci

      - name: Build project
        run: |
          npm run build
        continue-on-error: true

      - name: Check files
        run: |
          pwd
          ls -la
  
      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: 64000
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/pilihan2/repositories/MemilihTanpaBebanUAT/
            ls -la
            rm -rf .next

      - name: Upload .next folder to cPanel server
        env:
          FTP_HOST: ${{ secrets.SERVER_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_HOST" <<-EOF
            set ssl:verify-certificate no
            mirror -R --delete --verbose \
              --exclude-glob node_modules/ \
              --exclude-glob public/ \
              --exclude-glob .git/ \
              /home/runner/work/MemilihTanpaBeban/MemilihTanpaBeban/ \
              /repositories/MemilihTanpaBebanUAT/
            bye
          EOF